title: zqzyz.com
encoding: "utf-8"
exclude: ["snowpack.config.js"]
include: ["CNAME","_snowpack"]

lsi: false
safe: true
source: build
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
