markdown: kramdown
pygments: true
title: zqzyz.com
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

exclude: [
  "snowpack.config.js"
]
include: ["CNAME"]
source: "src/build"
#destination: _site