repository: oft/oft.github.io
github_url: https://github.com/oft/oft.github.io
url: https://zqzyz.com
github: [metadata]

exclude: [
  "snowpack.config.js"
]
include: ["CNAME"]
source: "src/build"
#destination: _site