markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: ""

repository: https://github.com/oft/oft.github.io
help_url: https://github.com/jekyll/jekyll-help

# timezone: Asia/BeiJing

collections:
  docs:
    output: true

name: 前端资源
description: 前端资源
# url: http://jekyllrb.com
url: http://zqzyz.com

logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

host: 0.0.0.0
exclude: ["yarn.lock","package.json","CNAME"]